### ISSUE TITLE
windows7下怎么设置参数

### ISSUE THREAD

**Issue by g8up** [zh-five/MarkdownFormat#1]
在 win7 下的 sublimeText3 上体验，没有对齐：
![image](https://user-images.githubusercontent.com/8005686/34810496-ae59df3e-f6d6-11e7-835d-06b63ea4b85a.png)
是字体问题吗？

**Comment by g8up** [comment]
```
| 业务方向      | 线人         |
|:----------|:-----------|
| 运营后台 - 销售 | 雪、鹏、丽 |
| 智能商业部     | 瑞         |
```
处理这个表格时，提示“格式化了0个表格”

**Comment by zh-five** [comment]
注意表格前要一个空行或者是文件的开头才能被识别. 

我暂时没有找到win7系统做测试, 过两天我找个系统测试一下
你先检查以下两个方面:
1. 所使用的字体是否是等宽字体
2. 因为系统和字体的不同, 可能需要调整参数, 那两个宽度参数是否按README.md里的说明进行了调整.

**Comment by g8up** [comment]
果然，是参数设置问题。win7 下我修改成 `1 2`，表现良好！谢谢！
